polygons:
  - StopPolygon
polygons_dict:
  StopPolygon:
    type: "polygon"
    points: "[ [0.1, 0.1], [0.1, -0.1], [-0.1, -0.1], [-0.1, 0.1] ]"
    action_type: "stop"
    min_points: 4
    visualize: True
    polygon_pub_topic: "polygon_stop"
    enabled: True

planner_plugins:
  - GridBased
planner_plugins_dict:
  GridBased:
    plugin: "nav2_navfn_planner::NavfnPlanner"
    tolerance: 0.5
    use_astar: false
    allow_unknown: true

footprint: "[ [0.1, 0.1], [0.1, -0.1], [-0.1, -0.1], [-0.1, 0.1] ]"

odom_frame: 'odom'