controller_manager:
  ros__parameters:
    update_rate: 50            # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    wlp311e_velocity_controller:
      type: diff_drive_controller/DiffDriveController

wlp311e_velocity_controller:
  ros__parameters:
    # wheel joints defined in WLP311E.urdf.xacro
    left_wheel_names:  [ "LF_WHL", "LH_WHL" ]
    right_wheel_names: [ "RF_WHL", "RH_WHL" ]

    # values derived from the LF leg chain in WLP311E.urdf.xacro,
    # HAA y=0.065, HFE y=0.0363, KFE y=0.09075, WHL y=0.03459, summed and doubled
    wheel_separation: 0.453
    wheels_per_side: 2
    wheel_radius: 0.127

    wheel_separation_multiplier: 1.5
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint

    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [1000000.0, 1000000.0, 0.03, 1000000.0, 1000000.0, 0.03]

    open_loop: false
    enable_odom_tf: false
    cmd_vel_timeout: 0.25

    linear.x.has_velocity_limits:  true
    linear.x.max_velocity:         2.0
    linear.x.min_velocity:        -2.0
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration:    20.0
    linear.x.min_acceleration:   -20.0

    angular.z.has_velocity_limits:  true
    angular.z.max_velocity:         4.0
    angular.z.min_velocity:        -4.0
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration:    25.0
    angular.z.min_acceleration:   -25.0
